branches:
  only:
  - master

language: python
pyton: 3.7

install:
- pip install mkdocs
- pip install mkdocs-material

script:
- git clean -f -d -x

after_success:
- git config user.name "hansel-no-kioku"
- git config user.email "hansel-no-kioku@users.noreply.github.com"
- git remote add gh-token "https://${GH_TOKEN}@github.com/hansel-no-kioku/hansels-notes.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v -c -r gh-token;
