# Site information
site_name: ヘンゼルのノート
site_description: 主にプログラミング関連のメモ用
site_author: ヘンゼルの記憶
repo_url: https://github.com/hansel-no-kioku/hansels-notes

# Copyright
copyright: 'Copyright &copy; 2019 ヘンゼルの記憶'

# Google Analytics
google_analytics: ['G-HF18DX69BQ', 'notes.han-sel.com']

# Navigation
nav:
  - Home: index.md
  - phina.js:
    - 'ヒント':
      - 'phina.js のイベントの仕組み': phinajs/tips/how-to-use-event.md
      - 'phina.js のイベント一覧': phinajs/tips/event-list.md
      - 'phina.js でフレームレート(fps)やメモリ使用量を表示する': phinajs/tips/stats.md
      - 'phina.js の Shape での origin による座標計算は padding を含む': phinajs/tips/coordinates-of-shapes.md
  - PureScript:
    - 'PureScript 0.12.0 で何が変わったか':
      - 'Effect編': purescript/changes-in-0.12.0/effect.md
      - 'ST編': purescript/changes-in-0.12.0/st.md
      - 'レコード編': purescript/changes-in-0.12.0/record.md
    - 'ヒント':
      - 'Stateモナド': purescript/tips/state-monad.md
      - 'StateTモナド': purescript/tips/statet-monad.md
  - MkDocs:
    - 'Markdown チートシート': mkdocs/markdown.md
    - 'MkDocs+': mkdocs/mkdocsplus.md
  - About: about.md

# Theme
theme:
  name: material
  palette:
    primary: 'Deep Orange'
    accent: 'Deep Orange'
  icon:
    logo: material/text-box-multiple
    repo: fontawesome/brands/github-alt
  favicon: 'images/favicon.png'
  features:
    - search.highlight

plugins:
  - search:
      lang:
        - en
        - ja
  - git-revision-date-localized:
      type: date
      locale: en

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/hansel-no-kioku'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/hansel_no_kioku'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  # MathJax
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'
  # js-sequence-diagrams
  - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.5.1/snap.svg-min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js'
  - 'https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js'
  # mermaid
  - 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0/mermaid.min.js'
  # extra
  - 'javascripts/extra.js'

markdown_extensions:
  - extra # abbr attr_list def_list fenced_code footnotes tables
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
